import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [file, setFile] = useState()

  function updateFile(event) { setFile(event.target.files[0]) }

  function handleSubmit(event) {
    event.preventDefault()
    const data = new FormData();
    data.append('file', file)
  }

  return <div className='flex h-screen w-screen justify-center items-center'>
    <Head>
      <title>CloudBreeze</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <form onSubmit={handleSubmit} className="grid grid-cols-[auto_1fr] max-w-[400px] gap-3 place-content-center">
      <label htmlFor="file">File:</label>
      <input type="file" id='file' required onChange={updateFile} />
      <label htmlFor="password">Password:</label>
      <input type="password" id='password' className='border' />
      <button type="submit" className='col-span-2 border border-black rounded bg-gray-100'>Share</button>
    </form>
  </div>
}
