export const fetchHistory = ['/account', '/account/history']
export const hideNavbar = ['/_error', '/account/confirm/[token]']
export const showModal = ['/account', '/account/history', '/file/download', '/p2p']
export const onlyGuest = ['/account/signup', '/account/login', '/account/forgot']
export const options = { upload: 'Uploaded', transfer: 'Transferred', download: 'Downloaded' }
export const unavailable = Object.keys(options).concat('error')
export const types = ['normal', 'premium']
export const uselessErrors = ['e', 'ta']
const bitwise = { MB: 20, GB: 30 }// In power of 2
export const cloudLimitMB = 100 // In MB
export const cloudLimit = cloudLimitMB << bitwise.MB // In bytes
export const transferLimitGB = 2 // In GB
export const transferLimit = transferLimitGB << bitwise.GB // In bytes
export const peerOptions = { host: 'cloudbreeze-peer.onrender.com', secure: true, pingInterval: 5000 }
export const chunkSize = 1 << 17; // In bytes (128 KB)
export const maxBufferSize = 1 << bitwise.MB
export const regex = /^cloudbreeze_.*\.zip$/